<?php

declare(strict_types=1);

namespace Qscmf\Chat2Viz\Tests\Integration;

use PHPUnit\Framework\TestCase;
use Qscmf\Chat2Viz\Security\SqlValidator;

/**
 * Widget data query integration tests with Sakila SQL patterns.
 *
 * Tests the complete widget data query pipeline:
 *   1. Extract SQL from published schema
 *   2. Validate SQL (SELECT-only, no UNION, no multi-statement)
 *   3. Enforce LIMIT
 *   4. (In production: execute against database with timeout and caching)
 *
 * Each test maps to a specific prompt from sakila-test-prompts.md and verifies
 * that the SQL generated by NL2SQL would pass all security checks.
 *
 * @see sakila-test-prompts.md
 */
class WidgetDataQueryTest extends TestCase
{
    /**
     * Sample SQL patterns from all 20 Sakila test prompts.
     * These represent what the NL2SQL service would produce.
     */
    private const SAKILA_SQL_PATTERNS = [
        // Simple queries
        1 => 'SELECT COUNT(*) AS total FROM qs_film',
        2 => 'SELECT COUNT(*) AS total FROM qs_customer',
        3 => 'SELECT rating, COUNT(*) AS film_count FROM qs_film GROUP BY rating ORDER BY film_count DESC',
        4 => 'SELECT title, rental_rate FROM qs_film ORDER BY rental_rate DESC LIMIT 10',
        5 => 'SELECT AVG(rental_rate) AS avg_price FROM qs_film',

        // Medium queries
        6 => 'SELECT a.first_name, a.last_name, COUNT(fa.film_id) AS film_count FROM qs_actor a JOIN qs_film_actor fa ON a.actor_id = fa.actor_id GROUP BY a.actor_id, a.first_name, a.last_name ORDER BY film_count DESC LIMIT 5',
        7 => 'SELECT c.name AS category, COUNT(fc.film_id) AS film_count FROM qs_category c JOIN qs_film_category fc ON c.category_id = fc.category_id JOIN qs_film f ON fc.film_id = f.film_id GROUP BY c.category_id, c.name ORDER BY film_count DESC',
        8 => 'SELECT s.store_id, COUNT(c.customer_id) AS customer_count FROM qs_store s LEFT JOIN qs_customer c ON s.store_id = c.store_id GROUP BY s.store_id',
        9 => "SELECT DATE(p.payment_date) AS day, SUM(p.amount) AS daily_revenue FROM qs_payment p WHERE p.payment_date >= '2005-06-01' AND p.payment_date < '2005-07-01' GROUP BY DATE(p.payment_date) ORDER BY day",
        10 => 'SELECT f.title FROM qs_film f LEFT JOIN qs_inventory i ON f.film_id = i.film_id LEFT JOIN qs_rental r ON i.inventory_id = r.inventory_id WHERE r.rental_id IS NULL',

        // Complex queries
        11 => 'SELECT co.country, COUNT(c.customer_id) AS customer_count FROM qs_country co JOIN qs_city ci ON co.country_id = ci.country_id JOIN qs_address a ON ci.city_id = a.city_id JOIN qs_customer c ON a.address_id = c.address_id GROUP BY co.country_id, co.country ORDER BY customer_count DESC',
        12 => 'SELECT f.rating, AVG(p.amount) AS avg_rental_income FROM qs_film f JOIN qs_inventory i ON f.film_id = i.film_id JOIN qs_rental r ON i.inventory_id = r.inventory_id JOIN qs_payment p ON r.rental_id = p.rental_id GROUP BY f.rating ORDER BY avg_rental_income DESC',
        13 => 'SELECT c.first_name, c.last_name, SUM(p.amount) AS total_spent FROM qs_customer c JOIN qs_payment p ON c.customer_id = p.customer_id GROUP BY c.customer_id, c.first_name, c.last_name ORDER BY total_spent DESC LIMIT 10',
        14 => 'SELECT a.first_name, a.last_name FROM qs_actor a JOIN qs_film_actor fa ON a.actor_id = fa.actor_id JOIN qs_film_category fc ON fa.film_id = fc.film_id JOIN qs_category c ON fc.category_id = c.category_id WHERE c.name IN (\'Action\', \'Comedy\') GROUP BY a.actor_id, a.first_name, a.last_name HAVING COUNT(DISTINCT c.name) = 2',
        15 => "SELECT DATE_FORMAT(r.rental_date, '%Y-%m') AS month, COUNT(*) AS rental_count, SUM(p.amount) AS total_revenue FROM qs_rental r JOIN qs_payment p ON r.rental_id = p.rental_id WHERE r.rental_date BETWEEN '2005-05-01' AND '2005-08-31' GROUP BY DATE_FORMAT(r.rental_date, '%Y-%m') ORDER BY month",

        // Visualization queries
        16 => 'SELECT c.name AS category, COUNT(*) AS film_count FROM qs_category c JOIN qs_film_category fc ON c.category_id = fc.category_id GROUP BY c.name ORDER BY film_count DESC',
        17 => 'SELECT CASE WHEN length < 60 THEN \'Short (<60min)\' WHEN length BETWEEN 60 AND 120 THEN \'Medium (60-120min)\' ELSE \'Long (>120min)\' END AS duration_range, COUNT(*) AS film_count FROM qs_film GROUP BY duration_range ORDER BY duration_range',
        18 => "SELECT DATE_FORMAT(p.payment_date, '%Y-%m') AS month, SUM(p.amount) AS total_revenue FROM qs_payment p GROUP BY month ORDER BY month",
        19 => 'SELECT rating, COUNT(*) AS film_count FROM qs_film GROUP BY rating ORDER BY film_count DESC',
        20 => 'SELECT f.title, COUNT(r.rental_id) AS rental_count, SUM(p.amount) AS total_revenue FROM qs_film f JOIN qs_inventory i ON f.film_id = i.film_id JOIN qs_rental r ON i.inventory_id = r.inventory_id JOIN qs_payment p ON r.rental_id = p.rental_id GROUP BY f.film_id, f.title ORDER BY rental_count DESC LIMIT 10',
    ];

    // =========================================================================
    // All 20 Sakila SQL patterns pass validation
    // =========================================================================

    /**
     * @dataProvider sakilaSqlProvider
     */
    public function testSakilaSqlPassesValidation(int $promptId, string $sql): void
    {
        // Step 1: Validate SELECT-only
        SqlValidator::validateSelectOnly($sql);
        $this->assertTrue(true, "Prompt #{$promptId} SQL should pass SELECT validation");

        // Step 2: Enforce LIMIT (idempotent if already present)
        $limitedSql = SqlValidator::enforceLimit($sql, 1000);
        $this->assertStringContainsString('LIMIT', $limitedSql, "Prompt #{$promptId} SQL should have LIMIT");
    }

    /**
     * @dataProvider sakilaSqlProvider
     */
    public function testSakilaSqlCanBeExtractedFromSchema(int $promptId, string $sql): void
    {
        $widgetId = "widget-prompt-{$promptId}";
        $schema = [
            'widgets' => [
                ['id' => $widgetId, 'title' => "图表#{$promptId}", 'sql' => $sql],
            ],
        ];

        $extracted = $this->extractWidgetSql($schema, $widgetId);
        $this->assertSame($sql, $extracted, "Prompt #{$promptId} SQL should be extractable");
    }

    public static function sakilaSqlProvider(): array
    {
        $cases = [];
        foreach (self::SAKILA_SQL_PATTERNS as $id => $sql) {
            $cases["prompt #{$id}"] = [$id, $sql];
        }
        return $cases;
    }

    // =========================================================================
    // SQL injection attempts should be blocked
    // =========================================================================

    /**
     * These test that even if the NL2SQL service is compromised and produces
     * malicious SQL, the widget data endpoint would reject it.
     */
    public function testRejectsSqlInjectionViaUnion(): void
    {
        $maliciousSql = "SELECT title FROM qs_film UNION SELECT password FROM qs_staff";

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('UNION');
        SqlValidator::validateSelectOnly($maliciousSql);
    }

    public function testRejectsSqlInjectionViaSemicolon(): void
    {
        $maliciousSql = "SELECT * FROM qs_film; DROP TABLE qs_film";

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Multi-statement');
        SqlValidator::validateSelectOnly($maliciousSql);
    }

    public function testRejectsSqlInjectionViaIntoOutfile(): void
    {
        $maliciousSql = "SELECT * FROM qs_film INTO OUTFILE '/etc/passwd'";

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Disallowed');
        SqlValidator::validateSelectOnly($maliciousSql);
    }

    public function testRejectsSqlInjectionViaCommentPrefix(): void
    {
        $maliciousSql = "/* SELECT */ DROP TABLE qs_film";

        $this->expectException(\InvalidArgumentException::class);
        SqlValidator::validateSelectOnly($maliciousSql);
    }

    // =========================================================================
    // LIMIT enforcement on Sakila patterns
    // =========================================================================

    /**
     * Prompts without explicit LIMIT should have one appended.
     */
    public function testLimitAppendedToFullTableScan(): void
    {
        $sql = self::SAKILA_SQL_PATTERNS[1]; // SELECT COUNT(*) - no LIMIT needed but harmless
        $result = SqlValidator::enforceLimit($sql, 1000);
        $this->assertStringContainsString('LIMIT 1000', $result);
    }

    /**
     * Prompts with existing LIMIT should be preserved.
     */
    public function testExistingLimitPreserved(): void
    {
        $sql = self::SAKILA_SQL_PATTERNS[4]; // Already has LIMIT 10
        $result = SqlValidator::enforceLimit($sql, 1000);
        // Should NOT add another LIMIT
        $this->assertSame($sql, $result);
    }

    /**
     * Prompt #11 (country customers) without LIMIT should get one appended.
     */
    public function testLimitAppendedToCountryQuery(): void
    {
        $sql = self::SAKILA_SQL_PATTERNS[11];
        $result = SqlValidator::enforceLimit($sql, 1000);
        $this->assertStringContainsString('LIMIT 1000', $result);
    }

    // =========================================================================
    // Schema-level widget data extraction with all 20 patterns
    // =========================================================================

    /**
     * Test building a complete dashboard schema with all 20 Sakila widgets
     * and verifying each SQL can be extracted.
     */
    public function testFullDashboardSchemaExtraction(): void
    {
        $widgets = [];
        foreach (self::SAKILA_SQL_PATTERNS as $promptId => $sql) {
            $widgets[] = [
                'id' => "sakila-widget-{$promptId}",
                'title' => "Sakila图表#{$promptId}",
                'g2_spec' => ['type' => 'interval'],
                'sql' => $sql,
            ];
        }

        $schema = ['widgets' => $widgets, 'layout' => [], 'variables' => []];

        $this->assertCount(20, $schema['widgets']);

        // Verify every widget's SQL can be extracted
        foreach (self::SAKILA_SQL_PATTERNS as $promptId => $expectedSql) {
            $widgetId = "sakila-widget-{$promptId}";
            $extracted = $this->extractWidgetSql($schema, $widgetId);
            $this->assertSame(
                $expectedSql,
                $extracted,
                "Widget for prompt #{$promptId} SQL extraction failed",
            );
        }
    }

    /**
     * Test that SQL validation + LIMIT enforcement pipeline works end-to-end
     * for all 20 Sakila patterns.
     */
    public function testFullPipelineForAllPatterns(): void
    {
        foreach (self::SAKILA_SQL_PATTERNS as $promptId => $sql) {
            // Step 1: Validate
            SqlValidator::validateSelectOnly($sql);

            // Step 2: Enforce LIMIT
            $limitedSql = SqlValidator::enforceLimit($sql, 1000);

            // Step 3: Verify LIMIT exists
            $this->assertMatchesRegularExpression(
                '/\bLIMIT\s+\d+/i',
                $limitedSql,
                "Prompt #{$promptId}: SQL must have LIMIT after enforcement",
            );
        }
    }

    // =========================================================================
    // Helper methods
    // =========================================================================

    private function extractWidgetSql(array $schema, string $widgetId): ?string
    {
        $widgets = $schema['widgets'] ?? [];
        if (!is_array($widgets)) {
            return null;
        }

        foreach ($widgets as $widget) {
            if (!is_array($widget)) {
                continue;
            }
            if (($widget['id'] ?? '') === $widgetId) {
                $sql = $widget['sql'] ?? null;
                if (is_string($sql) && trim($sql) !== '') {
                    return $sql;
                }
                return null;
            }
        }

        return null;
    }
}
