/**
 * SSE Dashboard Event Types — bound to the cross-repo contract SSOT.
 *
 * declarative-frontend-adapter: the whole-tree protocol collapsed the
 * deprecated DASHBOARD_INIT / WIDGET_DATA_UPDATE / dashboard_patch /
 * WIDGET_UPDATE / WIDGET_REMOVE / dashboard_rollback / sql_generated /
 * data_preview events into a single DASHBOARD_REPLACE (contract §2).
 *
 * The SSEDashboardReplace interface below mirrors the Python repo's
 * contracts/typescript/contracts.ts (generated by scripts/gen_contracts.py
 * from the Pydantic SSEDashboardReplace model in app/api/schemas.py).
 *
 * ── Cross-repo sync (SCOPE-3) ────────────────────────────────────────────
 * Sync command (run in the Python repo qs-chat2viz):
 *   make gen-contracts            # regenerates contracts/typescript/contracts.ts
 * Then copy the generated SSEDashboardReplace block verbatim into the
 * CONTRACT-GENERATED region below.
 *
 * Drift detection (the safety net if the copy is forgotten):
 *   1. CI gate — the Python repo's contract-driven-foundation Phase 3 job
 *      diffs contracts/typescript/contracts.ts against the checked-in copy
 *      and fails on structural mismatch.
 *   2. Contract baseline — the authoritative event/payload shape lives in
 *      /var/www/qs-chat2viz/docs/contracts/declarative-dashboard-contract.md
 *      (SemVer v1.0.0); a MAJOR bump there is a breaking change that MUST be
 *      reflected here in the same change proposal.
 *   3. Type guard — isDashboardReplaceData() below narrows at runtime, so a
 *      drifted payload (missing layout/widgets) degrades to the default case
 *      rather than crashing.
 *
 * DO NOT hand-edit the interface field structure — only add type guards
 * / convenience helpers below the "generated" divider.
 */

// ── BEGIN CONTRACT-GENERATED (from Python Pydantic SSOT) ────────────────────
// AUTO-GENERATED by scripts/gen_contracts.py — DO NOT EDIT BY HAND.
// Source of truth: Python Pydantic models (app/api/schemas.py).
// NOTE: index signature added to satisfy Record<string, unknown> assignability
// in sse-parser.ts's SseEvent.data; this is a hand-supplement (allowed: it does
// not change field structure, only satisfies TS assignability).

/**
 * Whole-tree dashboard delivery event (contract §2).
 *
 * Single event for both generate and modify — Python's MergeScheduler is the
 * sole computation authority for layout/widgets/truncated/total. The frontend
 * replaces its store wholesale and reuses cached data for any widget whose
 * `data` is null (slim — its SQL did not change).
 */
export interface SSEDashboardReplace {
  layout: Array<{
    i: string;
    x: number;
    y: number;
    w: number;
    h: number;
  }>;
  widgets: Record<string, {
    widget_id: string;
    title: string;
    chart_type: string;
    status: 'success' | 'error' | 'empty';
    /** Present when status=success. The widget's SQL text. */
    sql?: string;
    /** Present when status=success. G2 config — MUST NOT contain inline data. */
    g2_spec?: Record<string, unknown>;
    /**
     * null = slim (the widget's SQL did not change, frontend reuses cached
     * data). Non-null = {rows, columns} fresh result needing re-render.
     */
    data?: { rows: Array<Record<string, unknown>>; columns: string[] } | null;
    /** Present when status=error. User-readable, no sensitive credentials. */
    error_msg?: string;
    truncated?: boolean;
    total?: number;
    /** P0-A: present when status=empty. Deterministic Chinese explanation. */
    data_explain?: string;
    /** P0-A: advisory flag — WHERE may reference a non-existent literal. */
    suspect_value_mismatch?: boolean;
  }>;
  /** LLM natural-language reply. */
  answer: string;
  /** P0-B: ≤3 derived follow-up question suggestions (may be empty array). */
  suggested_followups?: string[];
  [key: string]: unknown;
}

// ── END CONTRACT-GENERATED ──────────────────────────────────────────────────

// ── Convenience type guards / helpers (hand-written, may edit) ─────────────

/**
 * Type guard: narrow an SseEvent's data to the DASHBOARD_REPLACE payload.
 * Use in useSseStream.ts case 'DASHBOARD_REPLACE' for typed field access.
 */
export function isDashboardReplaceData(
  data: Record<string, unknown>,
): data is SSEDashboardReplace & Record<string, unknown> {
  return Array.isArray(data.layout) && data.widgets !== null && typeof data.widgets === 'object';
}
