/**
 * SSE Dashboard Event Types — bound to the cross-repo contract SSOT.
 *
 * The SSEWidgetUpdate / SSEWidgetRemove interfaces below are COPIED from
 * the Python repo's contracts/typescript/contracts.ts (generated by
 * scripts/gen_contracts.py from Pydantic models SSEWidgetUpdate /
 * SSEWidgetRemove in app/api/schemas.py). Structural drift is caught by
 * the contract-driven-foundation Phase 3 CI gate (contract-diff job).
 *
 * To update: re-run `make gen-contracts` in the Python repo, then copy
 * contracts/typescript/contracts.ts here (or regenerate via the CI job).
 * DO NOT hand-edit the interface field structure — only add type guards
 * / convenience helpers below the "generated" divider.
 */

// ── BEGIN CONTRACT-GENERATED (from Python Pydantic SSOT) ────────────────────
// AUTO-GENERATED by scripts/gen_contracts.py — DO NOT EDIT BY HAND.
// Source of truth: Python Pydantic models (app/api/schemas.py).
// NOTE: index signature added to satisfy Record<string, unknown> assignability
// in sse-parser.ts's SseEvent.data; this is a hand-supplement (allowed: it does
// not change field structure, only satisfies TS assignability).

export interface SSEWidgetUpdate {
  type?: string;
  widget_id: string;
  action: string;
  field?: unknown;
  value?: unknown;
  schema_version?: string;
  [key: string]: unknown;
}

export interface SSEWidgetRemove {
  type?: string;
  widget_id: string;
  schema_version?: string;
  [key: string]: unknown;
}

// ── END CONTRACT-GENERATED ──────────────────────────────────────────────────

// ── Convenience type guards / helpers (hand-written, may edit) ─────────────

/**
 * Type guard: narrow an SseEvent's data to SSEWidgetUpdate.
 * Use in useSseStream.ts case 'WIDGET_UPDATE' for typed field access.
 */
export function isWidgetUpdateData(
  data: Record<string, unknown>
): data is SSEWidgetUpdate & Record<string, unknown> {
  return (
    typeof data.widget_id === 'string' &&
    typeof data.action === 'string'
  );
}

/**
 * Type guard: narrow an SseEvent's data to SSEWidgetRemove.
 */
export function isWidgetRemoveData(
  data: Record<string, unknown>
): data is SSEWidgetRemove & Record<string, unknown> {
  return typeof data.widget_id === 'string';
}

/**
 * Narrow `value` field of SSEWidgetUpdate by action semantics.
 * The `value` field is intentionally `unknown` in the contract because its
 * runtime type depends on `action`/`field` (e.g. set_type → string,
 * set_field → any JSON value). This helper centralizes the cast.
 */
export function widgetUpdateValue(update: SSEWidgetUpdate): unknown {
  return update.value;
}
